### ISSUE TITLE
SQL Import fails with Unknown column 'navigation_jumpTo'

### ISSUE THREAD

**Issue by Metis77** [erdmannfreunde/lasr-theme-bundle#1]
Contao 4.13.10
Theme: SIRIUS-EE-THEME-DEMO-1.11.1

On /contao/install the SQL import fails with:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'navigation_jumpTo' in 'field list‘
<img width="774" alt="import" src="https://user-images.githubusercontent.com/1408361/191914708-5bd020de-b038-4d5a-802b-db40ceca30f5.png">

**Comment by Metis77** [comment]
gelöst -> falsches theme Bundle installiert.

Ursache:
Jedes Theme verweist auf die selbe Doku.
Und jene Doku ist für das LASR Theme von euch.
https://erdmann-freunde.de/dokumentationen/contao-themes/theme-installieren/entwickler-edition/theme-mit-demo/ 

Folgt man dieser brav, installiert man immer:
php composer.phar require erdmannfreunde/lasr-theme-bundle

Anstatt zB:
php composer.phar require erdmannfreunde/sirius-theme-bundle

Hier sollte drauf hingewiesen werden, damit man da nicht stolpert.
Jetzt hat es perfekt geklappt.

**Comment by denniserdmann** [comment]
**Zur Info für andere Personen:**
In der Doku wird es wie folgt beschrieben:

> Installiere das jeweilige Theme-Bundle, zum Beispiel
>
> php composer.phar require erdmannfreunde/lasr-theme-bundle

`lasr` bezieht sich hierbei auf das LASR-Theme. Die anderen Themes lassen sich analog dazu installieren, wie von Metis77 beschrieben, tauscht man den Theme-Namen entsprechend aus.
