### ISSUE TITLE
Überlagerung durch mobile Navigation im Chrome 

### ISSUE THREAD

**Issue by mlwebworker** [erdmannfreunde/lasr-theme-bundle#2]
Contao 4.13.38
PHP 8.2.13
Lasr-Theme-Bundle 3.3.3

Im Chrome überdeckt die mobile Navigation bei nicht aktivem Zustand den Inhalt teilweise. Ab wann genau das so ist kann ich nicht sagen, aufgefallen ist es meinem Kunden nach dem Update auf Contao 4.13.38 (zuvor war 4.13.37).
Im Vivaldi, Microsoft -Edge (nur Windows) tritt das Problem auch auf. 
Im Firefox, Opera (nur Windows) und Safari (nur Mac) konnte ich es nich beobachten. Alle Browser waren bei meinem Test aktuell.

Das Problem ist auch auf Eurer Demoseite zu sehen.

![grafik](https://github.com/erdmannfreunde/lasr-theme-bundle/assets/3602676/02852ab3-e6fd-493e-8150-c93f2c4b0395)

**Comment by denniserdmann** [comment]
Moin Maren,

vielen Dank für den Hinweis, den ich auch bereits über Club bekam. Das Problem ist, das Chrome bzw. die Chrome-Engine eine CSS-Anweisung nun anders interpretiert. Du kannst das Problem wie folgt lösen: 

Wenn du in components/_navs.scss in ca. Zeile 38ff die Anweisung von 

`justify-self: end `

auf

`margin-left: auto; `

änderst, dann sollte die Desktop-Navigation weiterhin rechtsbündig ausgerichtet sein und gleichzeitig die mobile Navigation wieder funktionieren. Dabei nicht vergessen den Assets Cache über die Systemwartung zu leeren.

Ist der Fehler bei dir nun ebenfalls verschwunden?

**Comment by mlwebworker** [comment]
Ich teste das heute oder spätestens morgen. Da ich auf dem Liveserver die css-Dateien verwende muss ich erst mal meine Entwicklungsumgebung korrekt aufbauen (war zuvor gulp und jetzt nutze ich in der Regel webpack)

**Comment by denniserdmann** [comment]
Als „schnelle“ (wenn auch nicht ganz saubere) Lösung kannst du auch per Inline-Style folgendes setzen:

```
.nav--right {
  justify-self: normal;
  margin-left: auto;
}
```

**Comment by mlwebworker** [comment]
Ich habe bei einem Kunden die "saubere" Lösung eingebaut. Bei den anderen beiden erst Mal aus Zeitgründen die schnelle Lösung als "Quickfix"
Den Quickfix habe ich allerdings leicht verändert:
```
.nav--right {
  justify-self: unset;
  margin-left: auto;
}
```
Funktioniert aber natürlich beides.

**Comment by mlwebworker** [comment]
Danke noch mal für die schnelle Bereitstellung eines Fixes. Ich hätte da wohl eine ganze Weile gesucht, wenn ich es überhaupt gefunden hätte. Die unterschiedlich/neue Interpretation der Chrome-Engine ist wohl an mir vorbei gegangen.
